In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1233, 9729, 6705, 8970],
 [1233, 9729, 6705, 5750],
 [1233, 6615, 6705, 2265],
 [42, 3568, 6849, 6785, 502],
 [42, 3568, 6849, 6785, 9733],
 [6533, 1233, 3826, 6705, 3341],
 [130, 6445, 5645, 6785]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1233 9729 6705 8970]
 [   0    0    0    0 1233 9729 6705 5750]
 [   0    0    0    0 1233 6615 6705 2265]
 [   0    0    0   42 3568 6849 6785  502]
 [   0    0    0   42 3568 6849 6785 9733]
 [   0    0    0 6533 1233 3826 6705 3341]
 [   0    0    0    0  130 6445 5645 6785]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Shubh Agnihotri\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step


array([[[ 0.03180716,  0.03811617,  0.04450921,  0.04909189,
          0.01042761,  0.03436062, -0.00271642,  0.01832623,
         -0.00198347, -0.04518342],
        [ 0.03180716,  0.03811617,  0.04450921,  0.04909189,
          0.01042761,  0.03436062, -0.00271642,  0.01832623,
         -0.00198347, -0.04518342],
        [ 0.03180716,  0.03811617,  0.04450921,  0.04909189,
          0.01042761,  0.03436062, -0.00271642,  0.01832623,
         -0.00198347, -0.04518342],
        [ 0.03180716,  0.03811617,  0.04450921,  0.04909189,
          0.01042761,  0.03436062, -0.00271642,  0.01832623,
         -0.00198347, -0.04518342],
        [-0.03865547, -0.04138684, -0.02706544,  0.04198628,
         -0.00195158, -0.01458056, -0.01474879, -0.02447668,
         -0.03613915,  0.04495783],
        [ 0.03343109, -0.03975477,  0.03939405,  0.01072602,
          0.00020178, -0.04630251,  0.01564934, -0.00108641,
         -0.0017116 ,  0.01850149],
        [-0.03817377, -0.02476552,  0.0187698 , -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 1233, 9729, 6705, 8970])

In [16]:
model.predict(embedded_docs[0].reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[[ 0.03180716,  0.03811617,  0.04450921,  0.04909189,
          0.01042761,  0.03436062, -0.00271642,  0.01832623,
         -0.00198347, -0.04518342],
        [ 0.03180716,  0.03811617,  0.04450921,  0.04909189,
          0.01042761,  0.03436062, -0.00271642,  0.01832623,
         -0.00198347, -0.04518342],
        [ 0.03180716,  0.03811617,  0.04450921,  0.04909189,
          0.01042761,  0.03436062, -0.00271642,  0.01832623,
         -0.00198347, -0.04518342],
        [ 0.03180716,  0.03811617,  0.04450921,  0.04909189,
          0.01042761,  0.03436062, -0.00271642,  0.01832623,
         -0.00198347, -0.04518342],
        [-0.03865547, -0.04138684, -0.02706544,  0.04198628,
         -0.00195158, -0.01458056, -0.01474879, -0.02447668,
         -0.03613915,  0.04495783],
        [ 0.03343109, -0.03975477,  0.03939405,  0.01072602,
          0.00020178, -0.04630251,  0.01564934, -0.00108641,
         -0.0017116 ,  0.01850149],
        [-0.03817377, -0.02476552,  0.0187698 , -0.0